version: '3'
services:
  host:
    image: orangespacer/react-employment-hub-host
    ports:
      - "5000:5000"

  profile:
    image: orangespacer/react-employment-hub-profile
    ports:
      - "5001:5001"

  vacancies:
    image: orangespacer/react-employment-hub-vacancies
    ports:
      - "5002:5002"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host
      - profile
      - vacancies