version: '3'
services:
  host:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  profile:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  vacancies:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host
      - profile
      - vacancies